#pragma once

#include <string>
#include <optional>
#include <chrono>
#include <future>
#include <memory>
#include <Eigen/Dense>
#include <rclcpp/rclcpp.hpp>
#include <std_msgs/msg/string.hpp>

namespace franka_cartesian_control {
namespace ros_wrapper {

/**
 * @brief Synchronously fetches the URDF XML model string from the `/robot_description` topic.
 *
 * @details
 * In ROS 2 ros2_control, controller plugins instantiated inside `controller_manager` do not automatically
 * receive the `robot_description` parameter unless explicitly passed in the launch file.
 * The standard ROS 2 pattern is to subscribe to `/robot_description`, which is published with `transient_local`
 * Durability QoS (latched topic) by `robot_state_publisher`.
 *
 * To avoid blocking or interfering with the `controller_manager` multi-threaded executor, this helper spins
 * a dedicated isolated temporary node using a `SingleThreadedExecutor` until the latched message arrives.
 *
 * @param logger Logger instance to report timeout or connection errors.
 * @param timeout Maximum wait time for the URDF message (default: 5 seconds).
 * @return std::optional<std::string> URDF XML string if received, std::nullopt on timeout.
 */
inline std::optional<std::string> fetchRobotDescription(
    const rclcpp::Logger& logger,
    std::chrono::seconds timeout = std::chrono::seconds(5)) {
    auto temp_node = std::make_shared<rclcpp::Node>("franka_urdf_waiter");
    std::promise<std::string> urdf_promise;
    auto urdf_future = urdf_promise.get_future();

    auto sub = temp_node->create_subscription<std_msgs::msg::String>(
        "/robot_description", rclcpp::QoS(1).transient_local(),
        [&urdf_promise](const std_msgs::msg::String::SharedPtr msg) {
            urdf_promise.set_value(msg->data);
        });

    rclcpp::executors::SingleThreadedExecutor executor;
    executor.add_node(temp_node);

    auto status = executor.spin_until_future_complete(urdf_future, timeout);
    if (status != rclcpp::FutureReturnCode::SUCCESS) {
        RCLCPP_ERROR(logger, "Timed out waiting for /robot_description (5s) - is robot_state_publisher running?");
        return std::nullopt;
    }
    return urdf_future.get();
}

/**
 * @brief Dynamic Rigid Frame Transformation Aligner for Cartesian Trajectory Execution.
 *
 * @details
 * Problem Statement:
 * Demonstrations recorded via haptic devices (Geomagic Touch) or generated by DMPs are defined in their own
 * local coordinates (e.g. haptic workspace frame, where trajectory starts at (0,0,0)).
 * When the Cartesian controller is activated, the robot end-effector is at an arbitrary physical pose:
 *   (p_activation, q_activation) in the robot base frame (fer_link0).
 *
 * Solution (Rigid SE(3) Offset Anchoring):
 * On arrival of the FIRST trajectory target pose (p_raw,0, q_raw,0), this class computes a fixed rigid offset:
 *   p_offset = p_activation - p_raw,0
 *   q_offset = q_activation * q_raw,0^-1
 *
 * For all subsequent trajectory samples k:
 *   p_target,k = p_offset + p_raw,k
 *   q_target,k = (q_offset * q_raw,k).normalized()
 *
 * This anchors the demonstrated relative motion to wherever the robot actually starts, eliminating
 * initial jump discontinuities without modifying the learned DMP weights.
 */
class FrameAligner {
public:
    /**
     * @brief Resets the aligner upon controller activation.
     * @param initial_pos Physical end-effector position at activation.
     * @param initial_quat Physical end-effector orientation quaternion at activation.
     */
    void reset(const Eigen::Vector3d& initial_pos, const Eigen::Quaterniond& initial_quat) {
        activation_ee_position_ = initial_pos;
        activation_ee_orientation_ = initial_quat;
        alignment_captured_ = false;
        position_offset_.setZero();
        orientation_offset_.setIdentity();
    }

    /**
     * @brief Transforms a raw input target pose into the robot's base frame.
     * @param raw_pos Input raw position from DMP/device.
     * @param raw_quat Input raw orientation quaternion.
     * @param[out] aligned_pos Resulting aligned position in robot base frame.
     * @param[out] aligned_quat Resulting aligned orientation in robot base frame.
     * @param logger Optional logger pointer to log captured offset on first frame.
     */
    void align(const Eigen::Vector3d& raw_pos, const Eigen::Quaterniond& raw_quat,
               Eigen::Vector3d& aligned_pos, Eigen::Quaterniond& aligned_quat,
               rclcpp::Logger* logger = nullptr) {
        if (!alignment_captured_) {
            position_offset_ = activation_ee_position_ - raw_pos;
            orientation_offset_ = activation_ee_orientation_ * raw_quat.conjugate();
            alignment_captured_ = true;
            if (logger) {
                RCLCPP_INFO(*logger,
                            "Captured DMP->robot alignment: position offset = [%.3f, %.3f, %.3f] m",
                            position_offset_.x(), position_offset_.y(), position_offset_.z());
            }
        }
        aligned_pos = position_offset_ + raw_pos;
        aligned_quat = (orientation_offset_ * raw_quat).normalized();
    }

    /// @brief Returns true if the alignment offset has already been locked for the current activation cycle.
    bool isCaptured() const { return alignment_captured_; }

    /**
     * @brief Transforms a raw feedforward twist (demo-local frame, same frame as
     *        the raw_pos/raw_quat passed to align()) into the robot base frame.
     *
     * @details
     * Mirrors EXACTLY what align() does to each channel, not "the same rotation
     * applied to both" - align() treats position and orientation asymmetrically:
     *   aligned_pos  = position_offset_ + raw_pos       -> PURE TRANSLATION, no rotation
     *   aligned_quat = orientation_offset_ * raw_quat   -> PURE ROTATION (left-mult)
     * Differentiating each channel the same way it is composed:
     *  - Linear: position_offset_ is a constant translation and is never rotated
     *    by align(), so d(aligned_pos)/dt = d(raw_pos)/dt exactly - the raw linear
     *    velocity passes through UNCHANGED. (An earlier version of this method
     *    rotated it by orientation_offset_ by analogy with the angular channel;
     *    that was wrong - measured ~68-93 deg between v_ff and the true target
     *    velocity, consistent with a spurious ~93 deg orientation_offset_ rotation
     *    being applied to a channel align() never rotates in the first place.)
     *  - Angular: aligned_quat = orientation_offset_ * raw_quat is a constant
     *    left-multiplication (fixed/base-frame rotation) applied to the whole
     *    orientation trajectory, so the corresponding angular velocity DOES
     *    transform: omega_aligned = R(orientation_offset_) * omega_raw (standard
     *    result for a fixed rotation composed onto a moving frame's world-frame
     *    angular velocity).
     *
     * Requires align() to have captured the offset first (isCaptured() true) -
     * calling this before the first align() would apply an identity rotation to
     * the angular channel silently, so callers must gate on isCaptured()
     * themselves (the controller already does: no velocity command is issued
     * before target_received_).
     */
    void alignVelocity(const Eigen::Vector3d& raw_linear, const Eigen::Vector3d& raw_angular,
                        Eigen::Vector3d& aligned_linear, Eigen::Vector3d& aligned_angular) const {
        aligned_linear = raw_linear;
        aligned_angular = orientation_offset_ * raw_angular;
    }

private:
    bool alignment_captured_ = false;
    Eigen::Vector3d position_offset_ = Eigen::Vector3d::Zero();
    Eigen::Quaterniond orientation_offset_ = Eigen::Quaterniond::Identity();
    Eigen::Vector3d activation_ee_position_ = Eigen::Vector3d::Zero();
    Eigen::Quaterniond activation_ee_orientation_ = Eigen::Quaterniond::Identity();
};

}  // namespace ros_wrapper
}  // namespace franka_cartesian_control
