# Synchronised recording stack, launched as a subprocess by
# demo_replay_sync_orchestrator (mode:=demo).
#
# Same two nodes as live_demo.launch.py, with three differences:
#   1. a MANDATORY `run_id` launch argument threads through the output file
#      names (absolute paths: demo_raw_<run_id>.csv, dmp_weights_<run_id>.yaml);
#   2. live_demo_recorder_node's button input is remapped
#      /touch0/buttons -> /touch0/buttons_synced, so it reacts to the
#      orchestrator's time-shifted start/stop edges, not the raw device edges;
#   3. csv_master_pose_player_node (stand-in) keeps publishing raw
#      /touch0/buttons: the orchestrator intercepts those, delays by
#      sync_delay_sec (anchored to the target's first odometry sim-time), and
#      re-emits the equivalent edges on /touch0/buttons_synced.
#
# Does NOT bring up Gazebo or the Franka controller stack (impedance) - those
# run in the franka container and are assumed already active.

import os

from ament_index_python.packages import get_package_share_directory

from launch import LaunchDescription
from launch.actions import DeclareLaunchArgument, OpaqueFunction
from launch.conditions import IfCondition
from launch.substitutions import LaunchConfiguration
from launch_ros.actions import Node


def _nodes(context, *_args, **_kwargs):
    run_id = LaunchConfiguration('run_id').perform(context)
    if not run_id:
        raise RuntimeError(
            "demo_replay_sync.launch.py: 'run_id' is mandatory and must be "
            "non-empty. It is generated by demo_replay_sync_orchestrator and "
            "threaded through here - there is deliberately no default.")

    params_file = LaunchConfiguration('params_file').perform(context)
    use_csv_playback = LaunchConfiguration('use_csv_playback')

    ws_root = os.path.join(os.path.expanduser('~'), 'thesis_ws')
    demo_csv = os.path.join(ws_root, 'demo_raw_{}.csv'.format(run_id))
    weights_yaml = os.path.join(ws_root, 'dmp_weights_{}.yaml'.format(run_id))

    live_demo_recorder_node = Node(
        package='haptic_dmp_learning',
        executable='live_demo_recorder_node',
        name='live_demo_recorder_node',
        output='screen',
        parameters=[params_file, {
            # params.yaml carries no use_sim_time key, so it must be set here:
            # this node has only this->now() (no timers) but that still needs to
            # follow /clock for the demo timestamps / tau to be sim-time.
            'use_sim_time': True,
            'output_demo_csv_path': demo_csv,
            'output_yaml_path': weights_yaml,
        }],
        remappings=[('/touch0/buttons', '/touch0/buttons_synced')],
    )

    csv_master_pose_player_node = Node(
        package='haptic_dmp_learning',
        executable='csv_master_pose_player_node',
        name='csv_master_pose_player_node',
        output='screen',
        parameters=[params_file, {'use_sim_time': True}],
        condition=IfCondition(use_csv_playback),
    )

    return [live_demo_recorder_node, csv_master_pose_player_node]


def generate_launch_description():
    default_params_file = os.path.join(
        get_package_share_directory('haptic_dmp_learning'), 'config', 'params.yaml')

    return LaunchDescription([
        DeclareLaunchArgument(
            'run_id',
            description='Mandatory demo run identifier (no default). Threaded into '
                        'demo_raw_<run_id>.csv and dmp_weights_<run_id>.yaml.'),
        DeclareLaunchArgument(
            'use_csv_playback', default_value='true',
            description='Launch csv_master_pose_player_node as a stand-in for the '
                        'Geomagic Touch driver.'),
        DeclareLaunchArgument(
            'params_file', default_value=default_params_file,
            description='YAML file with ros__parameters for both nodes.'),
        OpaqueFunction(function=_nodes),
    ])
