controller_manager:
  ros__parameters:
    update_rate: 1000  # Hz

    velocity_cartesian_controller:
      type: franka_cartesian_control/CartesianVelocityController

    cartesian_impedance_controller:
      type: franka_cartesian_control/CartesianImpedanceController

velocity_cartesian_controller:
  ros__parameters:
    joint_names:
      - fer_joint1
      - fer_joint2
      - fer_joint3
      - fer_joint4
      - fer_joint5
      - fer_joint6
      - fer_joint7
    ee_frame_name: fer_link8
    target_pose_topic: /target_pose
    kp_linear: 1.0
    kp_angular: 1.0
    damping_lambda: 0.05
    max_linear_speed: 0.15
    max_angular_speed: 0.5
    max_joint_speed: 1.5

cartesian_impedance_controller:
  ros__parameters:
    joint_names:
      - fer_joint1
      - fer_joint2
      - fer_joint3
      - fer_joint4
      - fer_joint5
      - fer_joint6
      - fer_joint7
    ee_frame_name: fer_link8
    target_pose_topic: /target_pose
    translational_stiffness: 1000.0
    rotational_stiffness: 150.0
    translational_damping: 44.5
    rotational_damping: 7.0
    nullspace_stiffness: 0.2
    joint1_nullspace_stiffness: 100.0
    delta_tau_max: 1.0
    nullspace_pinv_damping: 0.05
    compensate_gravity_internally: false
